name: Setup Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start RDP
    runs-on: windows-latest
    steps:
      - name: Set up RDP
        run: |
          Invoke-WebRequest -Uri "https://github.com/fires3as0n/GitHubActions-RDP/raw/main/install-rdp.ps1" -OutFile "install-rdp.ps1"
          Start-Process powershell -ArgumentList "Set-ExecutionPolicy Bypass -Scope Process -Force; .\install-rdp.ps1 -user <username> -pass <password> -rdp_port 3389" -Wait -NoNewWindow
      - name: Keep Alive
        run: |
          while (1) {Start-Sleep -Seconds 300}
